'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ventas_cabecera
    Public Property id_venta As Integer
    Public Property id_usuario As Integer
    Public Property id_numero As Integer
    Public Property fecha_venta As Date
    Public Property total_venta As Nullable(Of Decimal)

    Public Overridable Property NroFactura As NroFactura
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property Ventas_detalle As ICollection(Of Ventas_detalle) = New HashSet(Of Ventas_detalle)

End Class
