'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ventas__detalle
    Public Property id_detalle As Integer
    Public Property id_venta As Integer
    Public Property id_producto As Integer
    Public Property cantidad As Integer
    Public Property sub_total As Integer

    Public Overridable Property Productos As Productos
    Public Overridable Property Ventas_cabecera As Ventas_cabecera

End Class
