'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ventas_cabecera
    Public Property id_venta As Integer
    Public Property id_usuario As Integer
    Public Property id_cliente As Integer
    Public Property fecha_venta As Date
    Public Property total_venta As Integer

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property Ventas__detalle As ICollection(Of Ventas__detalle) = New HashSet(Of Ventas__detalle)

End Class
